"""Generate PWA icons for the Aarva web app.

Renders the wordmark "Aarva" (no period, no tagline) in cream on the
same deep coffee-brown background the website uses, at three sizes:

  - aarva/server/static/icons/icon-192.png        (Android manifest)
  - aarva/server/static/icons/icon-512.png        (Android manifest)
  - aarva/server/static/icons/apple-touch-icon.png (iOS, 180x180)

Colours mirror the Tailwind tokens defined in `base.html`:
  background  #1A1410  (night)
  text        #F5EEDF  (cream-text)

The podcast cover (3000x3000, `aarva/output/cover.png`) is a separate
artefact generated by `scripts/generate_logo.py` — these PWA icons no
longer derive from it; the web-app surface gets its own minimal mark
so the home-screen tile reads cleanly at thumbnail sizes.

Re-run any time the wordmark or palette evolves:

    python scripts/generate_pwa_icons.py

The script tries a chain of serif fonts. Best-case it finds Fraunces
(matches the website's editorial face if dropped at
`scripts/fonts/Fraunces-Bold.ttf`); otherwise it falls back to
Georgia (macOS) / DejaVu Serif (Linux). The geometry stays the same
across fonts; only the letterforms change.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("ERROR: Pillow not installed. Run: pip install pillow")
    sys.exit(1)


_REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = _REPO_ROOT / "aarva" / "server" / "static" / "icons"

# Palette — mirrors tailwind tokens in base.html. Keep in sync.
BG_COLOUR   = (26, 20, 16)      # #1A1410 night
TEXT_COLOUR = (245, 238, 223)   # #F5EEDF cream-text

# (filename, size_in_px)
TARGETS = [
    ("icon-192.png", 192),
    ("icon-512.png", 512),
    ("apple-touch-icon.png", 180),
]

# Font discovery — tried in order. First existing+usable entry wins.
FONT_CANDIDATES = [
    # path, index, label
    # Bundle Fraunces here to match the website's editorial face:
    (str(_REPO_ROOT / "scripts" / "fonts" / "Fraunces-Bold.ttf"), 0, "Fraunces Bold (bundled)"),
    # macOS bold serifs
    ("/Library/Fonts/Georgia Bold.ttf", 0, "Georgia Bold"),
    ("/System/Library/Fonts/Supplemental/Georgia Bold.ttf", 0, "Georgia Bold"),
    ("/System/Library/Fonts/Supplemental/Georgia.ttf", 0, "Georgia"),
    # Linux fallbacks
    ("/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf", 0, "DejaVu Serif Bold"),
    ("/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf", 0, "Liberation Serif Bold"),
    # Last resort: any bold face will at least render
    ("/System/Library/Fonts/Helvetica.ttc", 1, "Helvetica Bold"),
]


def find_font() -> tuple[str, int, str]:
    for path, index, label in FONT_CANDIDATES:
        if os.path.exists(path):
            try:
                ImageFont.truetype(path, 100, index=index)
                return path, index, label
            except (OSError, IndexError):
                continue
    raise RuntimeError(
        "No suitable serif font found. Drop Fraunces-Bold.ttf in "
        "scripts/fonts/ or install one of the candidates above."
    )


def _fit_font(draw: ImageDraw.ImageDraw, text: str, font_path: str,
              font_index: int, target_w: int, start_size: int) -> ImageFont.FreeTypeFont:
    """Auto-fit font size so `text` renders to <= target_w pixels wide."""
    size = start_size
    while size > 10:
        font = ImageFont.truetype(font_path, size, index=font_index)
        bbox = draw.textbbox((0, 0), text, font=font)
        if bbox[2] - bbox[0] <= target_w:
            return font
        size -= 2
    return ImageFont.truetype(font_path, 10, index=font_index)


def make_icon(size: int, font_path: str, font_index: int) -> Image.Image:
    img = Image.new("RGB", (size, size), BG_COLOUR)
    draw = ImageDraw.Draw(img)

    # Wordmark occupies ~70% of the icon width — leaves a comfortable
    # margin at small thumbnail sizes (iOS rounds the corners, so the
    # edges of the letterforms shouldn't get clipped).
    target_w = int(size * 0.70)
    font = _fit_font(draw, "Aarva", font_path, font_index, target_w, start_size=size)

    bbox = draw.textbbox((0, 0), "Aarva", font=font)
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]

    # Centre horizontally and (optically) vertically. The bbox top/left
    # are non-zero for descenders + side bearings; subtract them so the
    # rendered glyphs end up centred, not the bbox.
    x = (size - text_w) // 2 - bbox[0]
    y = (size - text_h) // 2 - bbox[1]

    draw.text((x, y), "Aarva", fill=TEXT_COLOUR, font=font)
    return img


def main() -> None:
    font_path, font_index, font_label = find_font()
    print(f"Using font: {font_label}  ({font_path}, index={font_index})")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for filename, size in TARGETS:
        icon = make_icon(size, font_path, font_index)
        out = OUT_DIR / filename
        icon.save(out, "PNG", optimize=True)
        print(f"  Wrote: {out}  ({size}x{size})")


if __name__ == "__main__":
    main()
